// vue/src/lib/EditableList.vue
<script setup lang="ts">
import { ref, onMounted, PropType } from 'vue'

import { initListEditable } from '$core/index'

interface IProps<TypeItem = unknown> {
  items: PropType<TypeItem[]>
}
defineProps<IProps>()

const listRef = ref<HTMLDivElement | null>(null)

onMounted(() =>
  initListEditable({
    listEl: listRef.value,
  })
)
</script>

<template>
  <div ref="listRef">
    <div v-for="item in items">
      <slot name="item" v-bind="item"></slot>
    </div>
  </div>
</template>

// react/src/lib/EditableList.tsx
import { ReactElement, useEffect, useRef } from 'react'
import { initListEditable } from '$core/index'
import type { ListEditableOptions } from '$core/type'

interface IProps<TypeItem = unknown>
  extends Omit<ListEditableOptions<TypeItem>, 'listEl'> {
  getKey: (item: TypeItem) => string | number
  renderItem: (item: TypeItem) => ReactElement
}

export default function EditableList<TypeItem = unknown>(
  options: IProps<TypeItem>
) {
  const listRef = useRef<HTMLDivElement>(null)
  const { items, getKey, renderItem } = options

  useEffect(() => initListEditable({ ...options, listEl: listRef.current }), [])

  return (
    <div ref={listRef}>
      {items?.map((item) => (
        <div key={getKey(item)}>{renderItem(item)}</div>
      ))}
    </div>
  )
}
