// react/src/example/Basic.tsx
import { useState } from 'react'

import fakeItems from './items'
import EditableList from '$lib/EditableList'

const Basic = () => {
  const [items, setItems] = useState(fakeItems)

  return (
    <EditableList
      items={items}
      getKey={(item) => item.key}
      onChange={setItems}
      renderItem={(item) => <>{item.name}</>}
    />
  )
}

export default Basic

// svelte/src/example/Basic.svelte
<script lang="ts">
  import EditableList from '$lib/EditableList.svelte'
  import { faker } from '@faker-js/faker'

  const items = [...Array(6)].map((u, i) => ({
    name: faker.name.firstName(),
    key: i,
  }))
</script>

<EditableList {items} let:item getKey={(item) => item.key}>
  {item.name}
</EditableList>
