// vue/src/example/Basic.vue
<script setup lang="ts">
import { ref } from 'vue'

import fakeItems from './items'
import EditableList from '$lib/EditableList.vue'

defineProps<{ msg: string }>()

const items = ref(fakeItems)
</script>

<template>
  <h1>{{ msg }}</h1>
  <EditableList :items="items">
    <template #item="{ name }">
      <span>{{ name }}</span>
    </template>
  </EditableList>
</template>

// react/src/example/Basic.tsx
import { useState } from 'react'

import fakeItems from './items'
import EditableList from '$lib/EditableList'

const Basic = () => {
  const [items, setItems] = useState(fakeItems)

  return (
    <EditableList
      items={items}
      getKey={(item) => item.key}
      onChange={setItems}
      renderItem={(item) => <>{item.name}</>}
    />
  )
}

export default Basic
