// vue/src/lib/EditableList.vue
<script setup lang="ts">
import { ref, onMounted, PropType } from 'vue'

import { initListEditable } from '$core/index'

interface IProps<TypeItem = unknown> {
  items: PropType<TypeItem[]>
}
defineProps<IProps>()

const listRef = ref<HTMLDivElement | null>(null)

onMounted(() =>
  initListEditable({
    listEl: listRef.value,
  })
)
</script>

<template>
  <div ref="listRef">
    <div v-for="item in items">
      <slot name="item" v-bind="item"></slot>
    </div>
  </div>
</template>

// svelte/src/lib/EditableList.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { initListEditable } from '$core/index'

  type TypeItem = $$Generic
  interface $$Slots {
    default: { item: TypeItem }
  }

  let listEl: HTMLDivElement
  export let items: TypeItem[]
  export let getKey: (item: TypeItem) => string | number

  onMount(() =>
    initListEditable<TypeItem>({
      listEl,
      items,
      onChange: (newOrderItems) => (items = newOrderItems),
    })
  )
</script>

<div bind:this={listEl}>
  {#each items as item (getKey(item))}
    <div>
      <slot {item}>{JSON.stringify(item)}</slot>
    </div>
  {/each}
</div>
